# Generated by Django 3.0.2 on 2020-02-08 21:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, to='p_library.Friend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friend',
            name='borrowed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи книги'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Кому одолжил(Имя)'),
        ),
    ]
